import type { Metadata } from "next";
import "./globals.css";
import Header from "@/app/Navbar/Header";
import Footer from "./Footer/Footer";

export const metadata: Metadata = {
  title: "Kids Storyland",
  description: "Generated by Kids Storyland",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="p-3">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
